# create your drupal and postgres config here, based off the last assignment
version: '3'

services:
  drupal:
    image: drupal:9
    ports:
      - 8080:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    # restart: always
  postgres:
    image: postgres:10
    # restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    # ports:
    #   - '5432:5432'
    # volumes: 
    #   - db:/var/lib/postgresql/data
volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites: